import Head from "next/head";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import GetStarted from "@/components/GetStarted";
import OurPlans from "@/components/OurPlans";
import FeaturedIn from "@/components/FeaturedIn";
import WhyDiaspora from "@/components/WhyDiaspora";
import OnDemand from "@/components/OnDemand";

import affordableCare from "@/assets/img/affordable-care.png";
import Image from "next/image";

export default function Pricing() {
  return (
    <>
      <Head>
        <title>GeroCare - Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Navigation />

      <header className="header header--affordable-care">
        <div className="row">
          <div className="affordable-care">
            <div className="affordable-care__content">
              <h1 className="heading heading--display">
                Affordable Care. Trusted Doctors. Real Peace of Mind.
              </h1>

              <p>
                You want your parents safe, healthy, and cared for. Whether it’s
                a monthly check-in, an urgent visit, or a quick call—you can
                choose what they need, when they need it.
              </p>
            </div>

            <div className="affordable-care__img">
              <Image src={affordableCare} alt="Affordable Care" />
            </div>
          </div>
        </div>
      </header>

      <main>
        <OnDemand />

        <OurPlans />

        <WhyDiaspora />

        <GetStarted />

        <FeaturedIn />
      </main>

      <Footer />
    </>
  );
}
