import Head from "next/head";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import GetStarted from "@/components/GetStarted";
import Prices from "@/components/Pricing";

export default function Pricing() {
  return (
    <>
      <Head>
        <title>GeroCare - Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Navigation />

      <header className="header header--pricing">
        <div className="row">
          <h1 className="heading heading--display">Pricing Page</h1>
          <p>
            Subscription entitles patient to one doctor visit per month as a
            routine as needed valid for the subscribed duration. Time line for
            first appointment - 3 Working days for patient to be matched to a
            doctor and first appointment scheduled.
          </p>
        </div>
      </header>

      <main>
        <Prices />
        <GetStarted />
      </main>

      <Footer />
    </>
  );
}
