import Head from "next/head";
import Logo from "@/components/Logo";
import FormikStepper, { FormikStep } from "@/components/FormikStepper";
import * as Yup from "yup";
import { useContext, useRef, useState } from "react";
import { ProgressContext } from "@/context/progress";
import InputField from "@/components/InputField";
import ProgressBar from "@/components/ProgressBar";
import { FieldArray } from "formik";
import Image from "next/image";
import SelectField from "@/components/SelectField";
import PaymentMethod from "@/components/PaymentMethod";
import {
  ElderlyHomeVisit,
  HMO,
  OnDemandService,
  TeleConsultation,
} from "@/components/ChoosePlan";
import Link from "next/link";

const Register = () => {
  const { progress } = useContext(ProgressContext);
  const [formikState, setFormikState] = useState();
  const [service, setService] = useState();

  const serviceRef = useRef();

  const getFormikState = (values) => {
    setFormikState(values);
  };

  const handleServiceChange = (e) => {
    setService(serviceRef.current.value);
    console.log(serviceRef.current.value);
  };

  const initialValues = {
    firstname: "",
    lastname: "",
    email: "",
    password: "",
    confirmPassword: "",
    beneficiaryDetails: [
      {
        firstname: "",
        lastname: "",
        dateOfBirth: "",
        gender: "",
        email: "",
        phone: "",
        state: "",
        lga: "",
        address: "",
      },
    ],
    choosePlan: {
      plan: "",
      paymentMethod: "",
    },
  };

  const onSubmit = async (values, { resetForm }, onSubmitProps) => {
    console.log(values);
  };

  const genderOptions = [
    { value: "Select Gender" },
    { value: "Male" },
    { value: "Female" },
    { value: "Others" },
  ];

  const choosePlanOptions = [
    { value: "Select" },
    { value: "Phone Consultation" },
    { value: "Elderly Home Visits" },
    { value: "On Demand Service" },
    { value: "HMO" },
  ];

  const numberOfVisitsOptions = [{ value: "Select" }];

  const frequencyOfVisitsOptions = [{ value: "Select" }];

  const options = [
    {
      id: "paystack",
      paymentMethod: (
        <Image
          src={require("@/assets/img/paystack-2.png").default}
          alt="Paystack Logo"
        />
      ),
    },
    {
      id: "paypal",
      paymentMethod: (
        <Image
          src={require("@/assets/img/paypal-2.png").default}
          alt="PayPal Logo"
        />
      ),
    },
    {
      id: "stripe",
      paymentMethod: (
        <Image
          src={require("@/assets/img/stripe.png").default}
          alt="Stripe Logo"
        />
      ),
    },
    {
      id: "flutterwave",
      paymentMethod: (
        <Image
          src={require("@/assets/img/flutterwave.png").default}
          alt="Flutterwave Logo"
        />
      ),
    },
  ];

  return (
    <>
      <Head>
        <title>GeroCare - Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
          rel="stylesheet"
        />
      </Head>

      {/* <nav className="register__nav">
        <div className="row">
          <Logo />

          <div className="register__progress">
            <ProgressBar value={progress} />
          </div>

          <div className="register__empty">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </div>
        </div>
      </nav> */}
      <div className="auth__container">
        <div className="auth__left"></div>
        <div className="auth__right">
          <Logo />

          <header className="auth__header">
            <h4 className="heading heading--4">Create Account</h4>
            <p>
              Already have an account?{" "}
              <Link className="form__link" href={"/register"}>
                Login
              </Link>{" "}
            </p>

            <div className="register__progress">
              <ProgressBar value={progress} />
            </div>
          </header>

          <FormikStepper initialValues={initialValues} onSubmit={onSubmit}>
            <FormikStep getFormikState={getFormikState}>
              <div className="register__form">
                <div className="form__flex">
                  <InputField
                    type={"text"}
                    id={"firstname"}
                    name={"firstname"}
                    label={"First name"}
                    placeholder={"First name"}
                  />

                  <InputField
                    type={"text"}
                    id={"lastname"}
                    name={"lastname"}
                    label={"Last name"}
                    placeholder={"Last name"}
                  />
                </div>

                <InputField
                  type={"email"}
                  id={"email"}
                  name={"email"}
                  label={"Email Address"}
                  placeholder={"same@gmail.com"}
                />

                <InputField
                  type={"text"}
                  id={"phoneNumber"}
                  name={"phoneNumber"}
                  label={"Phone Number"}
                  placeholder={"70xxxxxxxx"}
                />

                <div className="form__flex">
                  <InputField
                    type={"text"}
                    id={"referralCode"}
                    name={"referralCode"}
                    label={"Referral Code"}
                    placeholder={"Enter referral code"}
                  />

                  <SelectField
                    options={genderOptions}
                    id={"aboutUs"}
                    name={`aboutUs`}
                    label={"Where did you hear about us?"}
                  />
                </div>

                <InputField
                  type={"password"}
                  id={"password"}
                  name={"password"}
                  label={"Create Password"}
                  placeholder={"**************"}
                />

                <InputField
                  type={"password"}
                  id={"confirmPassword"}
                  name={"confirmPassword"}
                  label={"Confirm Password"}
                  placeholder={"**************"}
                />
              </div>
            </FormikStep>

            <FormikStep getFormikState={getFormikState}>
              <div className="register__form">
                <div className="register__header">
                  <h4 className="heading heading--7">Beneficiary Details</h4>
                </div>

                <FieldArray
                  name="beneficiaryDetails"
                  render={({ push }) => (
                    <>
                      {formikState?.values.beneficiaryDetails &&
                      formikState?.values.beneficiaryDetails.length > 0 ? (
                        <>
                          {formikState?.values.beneficiaryDetails.length > 0 &&
                            formikState?.values.beneficiaryDetails.map(
                              (_, index) => (
                                <>
                                  <div key={index}>
                                    <div className="form__flex">
                                      <InputField
                                        type={"text"}
                                        id={"beneficiaryFirstname"}
                                        name={`beneficiaryDetails.${index}.firstname`}
                                        label={"First Name"}
                                        placeholder={"First name"}
                                      />

                                      <InputField
                                        type={"text"}
                                        id={"beneficiaryLastname"}
                                        name={`beneficiaryDetails.${index}.lastname`}
                                        label={"Last Name"}
                                        placeholder={"Last name"}
                                      />
                                    </div>

                                    <div className="form__flex">
                                      <InputField
                                        type={"date"}
                                        id={"beneficiaryDateOfBirth"}
                                        name={`beneficiaryDetails.${index}.dateOfBirth`}
                                        label={"Date of Birth"}
                                        placeholder={"First name"}
                                      />

                                      <SelectField
                                        options={genderOptions}
                                        id={"beneficiaryGender"}
                                        name={`beneficiaryDetails.${index}.gender`}
                                        label={"Gender"}
                                      />
                                    </div>

                                    <div className="form__flex">
                                      <InputField
                                        type={"email"}
                                        id={"beneficiaryEmail"}
                                        name={`beneficiaryDetails.${index}.email`}
                                        label={"Email Address"}
                                        placeholder={"email@example.com"}
                                      />

                                      <InputField
                                        type={"number"}
                                        id={"beneficiaryPhone"}
                                        name={`beneficiaryDetails.${index}.phone`}
                                        label={"Phone Number"}
                                        placeholder={"+234"}
                                      />
                                    </div>

                                    <div className="form__flex">
                                      <InputField
                                        type={"text"}
                                        id={"beneficiaryState"}
                                        name={`beneficiaryDetails.${index}.state`}
                                        label={"State"}
                                        placeholder={"State"}
                                      />

                                      <InputField
                                        type={"text"}
                                        id={"beneficiaryLga"}
                                        name={`beneficiaryDetails.${index}.lga`}
                                        label={"LGA"}
                                        placeholder={"LGA"}
                                      />
                                    </div>

                                    <InputField
                                      type={"text"}
                                      id={"beneficiaryAddress"}
                                      name={`beneficiaryDetails.${index}.address`}
                                      label={"Home Address"}
                                      placeholder={"Address"}
                                    />
                                  </div>
                                </>
                              )
                            )}
                          <button
                            onClick={() =>
                              push({
                                firstname: "",
                                lastname: "",
                                dateOfBirth: "",
                                gender: "",
                                phone: "",
                                state: "",
                                lga: "",
                                address: "",
                              })
                            }
                            type="button"
                            className="btn register__text-link"
                          >
                            <Image
                              src={require("@/assets/img/plus_icon.svg")}
                              alt="plus icon"
                            />
                            <span>Add Beneficiary</span>
                          </button>
                        </>
                      ) : (
                        <button
                          onClick={() =>
                            push({
                              firstname: "",
                              lastname: "",
                              dateOfBirth: "",
                              gender: "",
                              email: "",
                              phone: "",
                              state: "",
                              lga: "",
                              address: "",
                            })
                          }
                          type="button"
                          className="register__text-link"
                        >
                          <Image
                            src={require("@/assets/img/plus_icon.svg")}
                            alt="plus icon"
                          />
                          <span>Add Beneficiary</span>
                        </button>
                      )}
                    </>
                  )}
                />
              </div>
            </FormikStep>

            <FormikStep getFormikState={getFormikState}>
              <div className="register__form">
                <SelectField
                  ref={serviceRef}
                  options={choosePlanOptions}
                  id={"choosePlan"}
                  name={`choosePlan`}
                  label={"Choose a Service"}
                  onChange={handleServiceChange}
                />

                {service === "Phone Consultation" && (
                  <div className="register__plan-options">
                    {<TeleConsultation />}
                  </div>
                )}

                {service === "Elderly Home Visits" && (
                  <div className="register__plan-options">
                    <ElderlyHomeVisit />
                  </div>
                )}

                {service === "On Demand Service" && (
                  <div className="register__plan-options">
                    <OnDemandService />
                  </div>
                )}

                {service === "HMO" && (
                  <div className="register__plan-options">
                    <HMO />
                  </div>
                )}

                <div className="form__flex">
                  <SelectField
                    // ref={serviceRef}
                    options={numberOfVisitsOptions}
                    id={"numberOfVisits"}
                    name={`numberOfVisits`}
                    label={"Number of Visits"}
                  />
                  <SelectField
                    // ref={serviceRef}
                    options={frequencyOfVisitsOptions}
                    id={"frequencyOfVisits"}
                    name={`choosePlan`}
                    label={"Choose a Service"}
                    onChange={handleServiceChange}
                  />
                </div>

                <PaymentMethod
                  options={options}
                  label={"Select Payment Method"}
                  name={"paymentMethod"}
                />

                <p>
                  By submitting, I accept GeroCare’s{" "}
                  <Link className="form__link" href={"/"}>
                    Terms and Conditions
                  </Link>{" "}
                  and
                  <Link className="form__link" href={"/"}>
                    Privacy Policy.
                  </Link>
                </p>
              </div>
            </FormikStep>
          </FormikStepper>
        </div>
      </div>
    </>
  );
};

export default Register;
