import Head from "next/head";
import Navigation from "@/components/Navigation";
import Logo from "@/components/Logo";
import ProgressBar from "@/components/ProgressBar";
import FormikStepper, { FormikStep } from "@/components/FormikStepper";
import * as Yup from "yup";
import { useContext } from "react";
import { ProgressContext } from "@/context/progress";

const Register = () => {
  const { progress } = useContext(ProgressContext);

  const initialValues = {
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    confirmPassword: "",
  };

  const onSubmit = async (values, { resetForm }, onSubmitProps) => {
    console.log(values);
  };

  return (
    <>
      <Head>
        <title>GeroCare - Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
          rel="stylesheet"
        />
      </Head>

      <nav className="register__nav">
        <div className="row">
          <Logo />

          <div className="register__progress">
            <ProgressBar value={progress} />
          </div>

          <div className="register__empty"></div>
        </div>
      </nav>

      <FormikStepper initialValues={initialValues} onSubmit={onSubmit}>
        <FormikStep
          validationSchema={Yup.object({
            firstName: Yup.string().required(),
            lastName: Yup.string().required(),
            email: Yup.string().email().required(),
            password: Yup.string().min(8).required(),
          })}
        >
          Step 1
        </FormikStep>
        <FormikStep>Step 2</FormikStep>
        <FormikStep>Step 3</FormikStep>
      </FormikStepper>
    </>
  );
};

export default Register;
