import React from "react";
import Head from "next/head";
import Logo from "@/components/Logo";
import ProgressBar from "@/components/ProgressBar";
import FormikStepper, { FormikStep } from "@/components/FormikStepper";
import * as Yup from "yup";
import { useContext, useState } from "react";
import { ProgressContext } from "@/context/progress";
import InputField from "@/components/InputField";

const RequestCare = () => {
  const { progress } = useContext(ProgressContext);

  const initialValues = {
    healthCondition: "",
    preferenceDescription: "",
    services: "",
    existingCustomer: "",
    bookingCapacity: "",
    sponsporDetails: {
      firstname: "",
      lastname: "",
      email: "",
      phone: "",
      country: "",
      state: "",
      lga: "",
      city: "",
    },
    beneficiaryDetails: {
      firstname: "",
      lastname: "",
      dateOfBirth: "",
      gender: "",
      phone: "",
      email: "",
      address: "",
      state: "",
      lga: "",
    },
    emergencyContact: {
      firstname: "",
      lastname: "",
      email: "",
      phone: "",
      address: "",
      state: "",
      lga: "",
      workPattern: "",
    },
    terms: false,
  };

  const onSubmit = async (values, { resetForm }, onSubmitProps) => {
    console.log(values);
  };
  return (
    <>
      <Head>
        <title>GeroCare - Home Care Request</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
          rel="stylesheet"
        />
      </Head>

      <nav className="register__nav">
        <div className="row">
          <Logo />

          <div className="register__progress">
            <ProgressBar value={progress} />
          </div>

          <div className="register__empty">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </div>
        </div>
      </nav>

      <FormikStepper initialValues={initialValues} onSubmit={onSubmit}>
        <FormikStep>Care Request 1</FormikStep>
        <FormikStep>Care Request 2</FormikStep>
        <FormikStep>Care Request 3</FormikStep>
      </FormikStepper>
    </>
  );
};

export default RequestCare;
