import Head from "next/head";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import Image from "next/image";
import OurServices from "@/components/OurServices";
import SimpleSteps from "@/components/SimpleSteps";
import Tabs from "@/components/Tab";

export default function Contact() {
  return (
    <>
      <Head>
        <title>GeroCare - Elderly Care</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Navigation />

      <header className="header header--elderly">
        <div className="row">
          <div className="header__elderly-text">
            <h1
              className="heading heading--1"
              data-aos="fade-up"
              data-aos-duration="2000"
            >
              Premium Health Care Services for the Elderly
            </h1>

            <p data-aos="fade-up" data-aos-duration="2000">
              At Gerocare, we have developed an elderly care program designed to
              enhance the health and wellness of the elderly.
            </p>

            <a
              href="/register"
              className="btn btn--main"
              data-aos="fade-up"
              data-aos-duration="2000"
            >
              Get Started
            </a>
          </div>

          <div className="header__elderly-img">
            <Image
              src={require("@/assets/img/elderly-care.png").default}
              alt={"Elderly care"}
              data-aos="fade-up"
              data-aos-duration="2000"
            />
          </div>
        </div>
      </header>

      <main>
        <section className="section section--subscription">
          <div className="row">
            <div className="subscription__caption">
              <h2
                className="heading heading--display"
                data-aos="fade-up"
                data-aos-duration="2000"
              >
                Subscription Plans
              </h2>

              <p data-aos="fade-up" data-aos-duration="2000">
                We also offer flexible subscription plans at affordable rates
              </p>
            </div>

            <div className="subscription__pricing">
              <Tabs />
            </div>
          </div>
        </section>

        <SimpleSteps />

        <section className="section section--access">
          <div className="row">
            <div className="access__grid">
              <div className="access__content">
                <h2
                  className="heading heading--1"
                  data-aos="fade-up"
                  data-aos-duration="2000"
                >
                  Making access to health care convenient for the elderly.
                </h2>

                <p data-aos="fade-up" data-aos-duration="2000">
                  Gerocare teleconsultation service has revolutionized the way
                  healthcare is provided by increasing access to more
                  clinicians, responding to urgent patient concerns, lowering
                  healthcare costs, and offering more practical options for
                  diagnosis and treatment.
                </p>

                <ul className="access__list">
                  <li
                    className="access__item"
                    data-aos="fade-up"
                    data-aos-duration="2000"
                  >
                    <Image
                      src={require("@/assets/img/circled-check-mark.svg")}
                      alt="Circled checked mark icon"
                    />

                    <span>
                      You don't have to drive to the doctor's office or clinic.
                    </span>
                  </li>

                  <li
                    className="access__item"
                    data-aos="fade-up"
                    data-aos-duration="2000"
                  >
                    <Image
                      src={require("@/assets/img/circled-check-mark.svg")}
                      alt="Circled checked mark icon"
                    />

                    <span>
                      You don’t have to sit in a waiting room for prolonged
                      hours when you're sick.
                    </span>
                  </li>

                  <li
                    className="access__item"
                    data-aos="fade-up"
                    data-aos-duration="2000"
                  >
                    <Image
                      src={require("@/assets/img/circled-check-mark.svg")}
                      alt="Circled checked mark icon"
                    />

                    <span>
                      You can access a doctor from the comfort of your own bed
                      or sofa.
                    </span>
                  </li>
                </ul>

                <a
                  href="/register"
                  className="btn btn--main"
                  data-aos="fade-up"
                  data-aos-duration="2000"
                >
                  Sign Up for Free
                </a>
              </div>

              <div className="access__img">
                <Image
                  src={require("@/assets/img/senior-woman-meeting-with-male-doctor-cosmetic-surgeon-office@4x.png")}
                  data-aos="fade-up"
                  data-aos-duration="2000"
                />
              </div>
            </div>
          </div>
        </section>

        <OurServices />
      </main>

      <Footer />
    </>
  );
}
