import Head from "next/head";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

import Solutions from "@/components/Solutions";
import Services from "@/components/Services";
import Testimonials from "@/components/Testimonials";
import Awards from "@/components/Awards";
import Header from "@/components/Header";
import FeaturedIn from "@/components/FeaturedIn";
import CTA from "@/components/CTA";
import GetStarted from "@/components/GetStarted";
import Benefits from "@/components/Benefits";
import Metrics from "@/components/Metrics";
// import "../styles/main.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>GeroCare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Navigation />

      <Header />

      <main>
        <Awards />
        <Services />
        <Testimonials />
        <Solutions />
        <GetStarted />
        <Benefits />
        <Metrics />
        <FeaturedIn />
        <CTA />
      </main>

      <Footer />
    </>
  );
}
