import Head from "next/head";
import Navigation from "@/components/Navigation";

import Footer from "@/components/Footer";
import PaymentMethod from "@/components/PaymentMethod";
import Image from "next/image";

export default function Playground() {
  // const options = [
  //   {
  //     id: "paystack",
  //     paymentMethod: (
  //       <Image
  //         src={require("@/assets/img/paystack-2.png").default}
  //         alt="Paystack Logo"
  //       />
  //     ),
  //   },
  //   {
  //     id: "paypal",
  //     paymentMethod: (
  //       <Image
  //         src={require("@/assets/img/paypal-2.png").default}
  //         alt="PayPal Logo"
  //       />
  //     ),
  //   },
  //   {
  //     id: "stripe",
  //     paymentMethod: (
  //       <Image
  //         src={require("@/assets/img/stripe.png").default}
  //         alt="Stripe Logo"
  //       />
  //     ),
  //   },
  // ];

  return (
    <>
      <Head>
        <title>GeroCare - Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Navigation />

      {/* <SelectField
        options={options}
        id={"duration"}
        name={"duration"}
        label={"How long have you been in Business"}
      /> */}

      {/* <RadioBtnGroup
        options={existingConsumerOptions}
        label={"Are you an existing customer?"}
        name={"existingConsumer"}
      />

      <RadioBtnGroup
        options={bookingCapacityOptions}
        label={"In what capacity are you booking a Caregiver?"}
        name={"bookingCapacity"}
      />

      <CheckboxGroup
        options={selectServicesOptions}
        label={
          "Which of the following home care services are you seeking? (Services to be provided by the Caregiver Please tick all that apply)"
        }
        name={"services"}
      /> */}

      {/* <PaymentMethod
        options={options}
        label={"Select Payment Method"}
        name={"paymentMethod"}
      /> */}

      <Footer />

      {/* <header className="header">
      <div className="row">
        <h1 className="heading heading--1">Log In</h1>
      </div>
    </header> */}
    </>
  );
}
