import Head from "next/head";
import Navigation from "@/components/Navigation";

import Footer from "@/components/Footer";
import OurServices from "@/components/OurServices";
import SimpleSteps from "@/components/SimpleSteps";
import Image from "next/image";

const steps = [
  {
    step: 1,
    title: "Create an account",
    description: "Input your credentials to setup your personal account",
  },
  {
    step: 2,
    title: "Add a Beneficiary",
    description: "Provide the relevant details of your beneficiary",
  },

  {
    step: 3,
    title: "Select a plan",
    description: "Choose a subscription plan that suits your needs",
  },

  {
    step: 4,
    title: "Make Payment",
    description: "Proceed to payment and start enjoying our services",
  },
];

export default function Contact() {
  return (
    <>
      <Head>
        <title>GeroCare - Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Navigation />

      <section className="section section--access">
        <div className="row">
          <div className="access__grid">
            <div className="access__content">
              <h2 className="heading heading--1">
                Making access to health care convenient for the elderly.
              </h2>

              <p>
                Gerocare teleconsultation service has revolutionized the way
                healthcare is provided by increasing access to more clinicians,
                responding to urgent patient concerns, lowering healthcare
                costs, and offering more practical options for diagnosis and
                treatment.
              </p>

              <ul className="access__list">
                <li className="access__item">
                  <Image
                    src={require("@/assets/img/circled-check-mark.svg")}
                    alt="Circled checked mark icon"
                  />

                  <span>
                    You don't have to drive to the doctor's office or clinic.
                  </span>
                </li>

                <li className="access__item">
                  <Image
                    src={require("@/assets/img/circled-check-mark.svg")}
                    alt="Circled checked mark icon"
                  />

                  <span>
                    You don’t have to sit in a waiting room for prolonged hours
                    when you're sick.
                  </span>
                </li>

                <li className="access__item">
                  <Image
                    src={require("@/assets/img/circled-check-mark.svg")}
                    alt="Circled checked mark icon"
                  />

                  <span>
                    You can access a doctor from the comfort of your own bed or
                    sofa.
                  </span>
                </li>
              </ul>

              <a href="/register" className="btn btn--main">
                Sign Up for Free
              </a>
            </div>

            <div className="access__img">
              <Image
                src={require("@/assets/img/senior-woman-meeting-with-male-doctor-cosmetic-surgeon-office@4x.png")}
              />
            </div>
          </div>
        </div>
      </section>

      <Footer />

      {/* <header className="header">
      <div className="row">
        <h1 className="heading heading--1">Log In</h1>
      </div>
    </header> */}
    </>
  );
}
