import FAQs from "@/components/FAQs";
import Footer from "@/components/Footer";
import Navigation from "@/components/Navigation";
import Head from "next/head";

import { faqData } from "@/components/FAQs/faqData.js";

export default function Faqs() {
  return (
    <>
      <Head>
        <title>GeroCare - FAQs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Navigation />

      <header className="header header--elderly">
        <div className="row">
          <div className="header__elderly-text">
            <h1
              className="heading heading--1"
              data-aos="fade-up"
              data-aos-duration="2000"
            >
              Frequently Asked Questions
            </h1>

            <p data-aos="fade-up" data-aos-duration="2000">
              Have all of your questions answered. From Registration Processes,
              Payments and Doctor's Home Visits to other services and everything
              you need to know.
            </p>
          </div>
        </div>
      </header>

      <main>
        <FAQs data={faqData} />
      </main>

      <Footer />
    </>
  );
}
