import Logo from "@/components/Logo";
import Head from "next/head";
import Link from "next/link";
import React from "react";

const Success = () => {
  return (
    <>
      <Head>
        <title>GeroCare - Success</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div className="auth__container">
        <div className="auth__left"></div>
        <div className="auth__right">
          <div className="auth__logo-box auth__logo-box-lg">
            <Logo />
          </div>

          <header className="auth__header">
            <h4 className="heading heading--4">Password Reset Successfully</h4>
          </header>

          <Link href={"/login"} className="btn btn--main btn--full">
            Sign In
          </Link>
        </div>
      </div>
    </>
  );
};

export default Success;
